[package]
name = "euler-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
num-bigint = "0.3.1" # for Problems 16 and 20
permutations = "0.1.1" # for Problem 24, version 2