/*
Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

pub fn problem2() -> i32 {
    let mut a = 1;
    let mut b = 2;
    let mut sum = 0;

    while a < 4_000_000 {
        if a % 2 == 0 { sum += a }

        let c = a + b;
        a = b;
        b = c;
    }
    sum
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_problem2() {
        assert_eq!(problem2(), 4_613_732);
    }
}