/*
Problem 12:
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1+2+3+4+5+6+7 = 28. 
The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45,55, ...

Let us list the factors of the first seven triangle numbers:
1:1
3: 1,3
6: 1, 2, 3, 6
10: 1, 2, 5, 10
15:1, 3,5, 15
21: 1, 3, 7,21
28: 1, 2, 4, 7, 14, 28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/


fn _number_divisors(n: i32) -> i32 {
    // Simply checks every number below n -> high complexity
    let mut count = 0;
    for i in 1..n/2+1 {
        if n % i == 0 { count += 1; }
    }
    count
}

fn number_divisors_v2(n: i32) -> i32 {
    // Different approach: find the prime factors of n and returns
    // the product of the (primes valuations + 1)
    let mut current = n;
    let mut tot_div = 1;
    
    let mut i = 2;
    let mut count = 0;
    loop {
        if i > current { break; }
        if current % i == 0 {
            while current % i == 0 {
                current = current / i;
                count += 1;
            }
            tot_div *= count + 1;
            count = 0;
        }
        i += 1;
    }
    tot_div
}

pub fn problem12() -> i32 {
    let mut i = 1;
    let mut t = 1;

    loop {
        //let n = number_divisors(t);
        let n = number_divisors_v2(t);
        if n > 500 { break; }
        i += 1;
        t += i;
    }
    t
}